Repository petrkucerak/diecezko.cz, pull requests merged in 2023-10, with the labels that each got.

#128 New evzen score by `Pán Fojcek`
  _hall/1696246598611.json
Labels: evzen

#127 New evzen score by `Kajka`
  _hall/1696176031368.json
Labels: evzen

#124 New evzen score by `Ajuška `
  _hall/1696094350598.json
Labels: evzen

#122 New evzen score by `Regenschori ČL`
  _hall/1696094030458.json
Labels: evzen

#137 New evzen score by `Julča`
  _hall/1696324213768.json
Labels: evzen

#139 New evzen score by `Pedro`
  _hall/1696355405939.json
Labels: evzen

#138 New evzen score by `Daaveee_s_Praaheee`
  _hall/1696355319142.json
Labels: evzen

#136 New evzen score by `Julča`
  _hall/1696323372730.json
Labels: evzen

#121 New evzen score by `KK`
  _hall/1696093949628.json
Labels: evzen

#142 New evzen score by `Pán Fojcek`
  _hall/1696418779313.json
Labels: evzen

#141 New evzen score by `Pán Fojcek`
  _hall/1696417577104.json
Labels: evzen

#143 New evzen score by `Julča`
  _hall/1696506911845.json
Labels: evzen

#149 Update frontpage
  app/vikariaty/page.js
  components/cover.js
  components/faq.js
  components/layouts/faq-box.js
  components/layouts/faq-layout.js
  components/switcher/spolecenstvi-info.js
Labels: enhancement

#150 Add socials
  app/vikariaty/page.js
Labels: enhancement

#151 New evzen score by `Daaveee_s_Praaheee`
  _hall/1697199683368.json
Labels: evzen

#152 New evzen score by `Bětka`
  _hall/1697379090362.json
Labels: evzen

#155 New evzen score by `PeProOne`
  _hall/1697486080301.json
Labels: evzen

#154 New evzen score by `PeProOne`
  _hall/1697486071868.json
Labels: evzen

#156 Create rule for authorization nickname
  _hall/1695211768985.json
  _hall/1695219161288.json
  _hall/1695221885709.json
  _hall/1695223032577.json
  _hall/1695223042748.json
  _hall/1695223212061.json
  _hall/1695223344157.json
  _hall/1695239167132.json
  _hall/1695244963253.json
  _hall/1695281300783.json
  _hall/1695281693215.json
  _hall/1695289981233.json
  _hall/1695294038333.json
  _hall/1695313577329.json
  _hall/1695368323292.json
  _hall/1695379156230.json
  _hall/1695393447044.json
  _hall/1695393455858.json
  _hall/1695393456492.json
  _hall/1695393462533.json
  _hall/1695393472774.json
  _hall/1695393822983.json
  _hall/1695449250934.json
  _hall/1695577927419.json
  _hall/1695626490102.json
  _hall/1695719992296.json
  _hall/1695729617981.json
  _hall/1695743786349.json
  _hall/1695814171625.json
  _hall/1695842710138.json
  _hall/1695882950864.json
  _hall/1695882950958.json
  _hall/1695887237404.json
  _hall/1696093949628.json
  _hall/1696094030458.json
  _hall/1696094350598.json
  _hall/1696176031368.json
  _hall/1696246598611.json
  _hall/1696323372730.json
  _hall/1696324213768.json
  _hall/1696355319142.json
  _hall/1696355405939.json
  _hall/1696417577104.json
  _hall/1696418779313.json
  _hall/1696506911845.json
  _hall/1697199683368.json
  _hall/1697379090362.json
  _hall/1697486071868.json
  _hall/1697486080301.json
  components/game.js
  lib/request.js
Labels: enhancement, PRIORITY, evzen

#159 New evzen score by `Pedro`
  _hall/1697551695906.json
Labels: evzen

#158 Evzen adventure story
  app/jadro-diecezka/page.js
  components/game.js
  components/layouts/container-paragraph.js
  public/assets/images/jadro/evzen.png
  public/assets/images/jadro/evzen.webp
  public/assets/images/spolecenstvi/salas-cover.webp
Labels: enhancement, evzen

#166 New evzen score by `Animátoři`
  _hall/1697963780866.json
Labels: evzen

#167 New evzen score by `Animátoři`
  _hall/1697975683633.json
Labels: evzen

#168 New evzen score by `Animátoři`
  _hall/1697975692456.json
Labels: evzen

#169 New evzen score by `Animátoři`
  _hall/1697975701474.json
Labels: evzen

#170 Improve accesebility
  app/dcm-hradec-kralove/page.js
  app/prednasky-workshopy/page.js
  app/program-ve-filharmonii/page.js
  components/faq.js
  components/footer.js
  components/switcher/diecezko-info.js
  components/switcher/program.js
Labels: enhancement

#172 New evzen score by `Julča`
  _hall/1697996875651.json
Labels: evzen

#174 Update text and add link
  app/bistro-u-dvou-pratel/page.js
Labels: enhancement, content

#171 New evzen score by `Julča`
  _hall/1697996350277.json
Labels: evzen

#179 New evzen score by `Steve`
  _hall/1698180332877.json
Labels: evzen

#180 New evzen score by `Steve`
  _hall/1698180463640.json
Labels: evzen

#181 New evzen score by `Steve`
  _hall/1698180521634.json
Labels: evzen

#182 New evzen score by `Steve`
  _hall/1698180624598.json
Labels: evzen

#183 New evzen score by `Steve`
  _hall/1698180639270.json
Labels: evzen

#184 New evzen score by `Steve`
  _hall/1698181338730.json
Labels: evzen

#186 New evzen score by `Steve`
  _hall/1698181385747.json
Labels: evzen

#185 New evzen score by `Steve`
  _hall/1698181369739.json
Labels: evzen

#187 New evzen score by `Pedro`
  _hall/1698182146922.json
Labels: evzen

#197 Fix typo
  app/jadro-diecezka/page.js
  app/mse-svata/page.js
  app/studenecka-kapela/page.js
  components/game.js
  components/header.js
  components/switcher/diecezko-info.js
  components/switcher/program.js
  components/switcher/spolecenstvi-info.js
Labels: content

#188 Add countdown
  components/countdown.js
  components/switcher/diecezko-info.js
  lib/request.js
Labels: enhancement

#198 Fix typo
  app/dcm-hradec-kralove/page.js
  app/kak-salas/page.js
  app/prednasky-workshopy/page.js
  app/vikariaty/page.js
  components/faq.js
  components/game.js
  components/layouts/faq-box.js
  components/switcher/diecezko-info.js
  components/switcher/program.js
Labels: content

#207 New evzen score by `Lidu`
  _hall/1698338337866.json
Labels: evzen

#211 New evzen score by `Vévodkyně `
  _hall/1698577771354.json
Labels: evzen

#214 Add songs for final eucharistia
  app/mse-svata/page.js
Labels: content

#216 Update age limit
  components/faq.js
Labels: content

#218 Add TMM
  app/tyden-modliteb-za-mladez/page.js
  components/images/tmm.js
  components/switcher/spolecenstvi-info.js
  public/assets/images/tmm-logo.svg
Labels: enhancement, content

#219 New evzen score by `PePro`
  _hall/1698690394962.json
Labels: evzen

#220 New evzen score by `PePro`
  _hall/1698691225466.json
Labels: evzen
