Repository petrkucerak/diecezko.cz, pull requests merged in 2023-09, with the labels that each got.

#4 Improve cover page
  app/apple-icon.png
  app/globals.css
  app/layout.js
  app/page.js
  components/cover.js
  components/header.js
  components/meta.js
  components/switcher.js
  package.json
  public/assets/events/dcmhk23.ics
  yarn.lock
Labels: enhancement, content

#7 Create simple footer
  app/page.js
  components/footer.js
Labels: enhancement

#8 Create burger menu
  app/globals.css
  app/layout.js
  app/page.js
  components/header.js
  components/images/dcm-hk.js
  components/images/evzen.js
  components/images/salas.js
  components/images/veka.js
  components/images/vesmir.js
  components/switcher.js
  public/assets/images/dcm-white.svg
  public/assets/images/dczm-vesmir-white.svg
  public/assets/images/evzen-white.svg
  public/assets/images/salas-white.svg
  public/assets/images/veka-white.svg
Labels: enhancement

#10 Processing `bida from Petrova`
  app/evzenova-cesta/page.js
  app/globals.css
  app/page.js
  components/cover.js
  components/header.js
  components/switcher.js
  fonts/JosefinSans-Bold.woff
  fonts/JosefinSans-Bold.woff2
  fonts/JosefinSans-BoldItalic.woff
  fonts/JosefinSans-BoldItalic.woff2
  fonts/JosefinSans-ExtraLight.woff
  fonts/JosefinSans-ExtraLight.woff2
  fonts/JosefinSans-ExtraLightItalic.woff
  fonts/JosefinSans-ExtraLightItalic.woff2
  fonts/JosefinSans-Italic.woff
  fonts/JosefinSans-Italic.woff2
  fonts/JosefinSans-Light.woff
  fonts/JosefinSans-Light.woff2
  fonts/JosefinSans-LightItalic.woff
  fonts/JosefinSans-LightItalic.woff2
  fonts/JosefinSans-Medium.woff
  fonts/JosefinSans-Medium.woff2
  fonts/JosefinSans-MediumItalic.woff
  fonts/JosefinSans-MediumItalic.woff2
  fonts/JosefinSans-Regular.woff
  fonts/JosefinSans-Regular.woff2
  fonts/JosefinSans-SemiBold.woff
  fonts/JosefinSans-SemiBold.woff2
  fonts/JosefinSans-SemiBoldItalic.woff
  fonts/JosefinSans-SemiBoldItalic.woff2
  fonts/JosefinSans-Thin.woff
  fonts/JosefinSans-Thin.woff2
  fonts/JosefinSans-ThinItalic.woff
  fonts/JosefinSans-ThinItalic.woff2
  fonts/TitilliumWeb-Black.woff
  fonts/TitilliumWeb-Black.woff2
  fonts/TitilliumWeb-Bold.woff
  fonts/TitilliumWeb-Bold.woff2
  fonts/TitilliumWeb-BoldItalic.woff
  fonts/TitilliumWeb-BoldItalic.woff2
  fonts/TitilliumWeb-ExtraLight.woff
  fonts/TitilliumWeb-ExtraLight.woff2
  fonts/TitilliumWeb-ExtraLightItalic.woff
  fonts/TitilliumWeb-ExtraLightItalic.woff2
  fonts/TitilliumWeb-Italic.woff
  fonts/TitilliumWeb-Italic.woff2
  fonts/TitilliumWeb-Light.woff
  fonts/TitilliumWeb-Light.woff2
  fonts/TitilliumWeb-LightItalic.woff
  fonts/TitilliumWeb-LightItalic.woff2
  fonts/TitilliumWeb-Regular.woff
  fonts/TitilliumWeb-Regular.woff2
  fonts/TitilliumWeb-SemiBold.woff
  fonts/TitilliumWeb-SemiBold.woff2
  fonts/TitilliumWeb-SemiBoldItalic.woff
  fonts/TitilliumWeb-SemiBoldItalic.woff2
  public/assets/images/cover.jpg
  public/assets/images/cover.png
  public/assets/images/cover.webp
  tailwind.config.js
Labels: enhancement

#17 Create game evzenova cesta
  .github/workflows/holub-evzen.yml
  README.md
  app/evzenova-cesta/page.js
  app/globals.css
  components/footer.js
  components/game.js
  components/header.js
  lib/game.js
  lib/request.js
  package.json
  public/assets/images/game/PixelFood.png
  public/assets/images/game/airship_1.png
  public/assets/images/game/airship_2.png
  public/assets/images/game/airship_3.png
  public/assets/images/game/barbora.png
  public/assets/images/game/bg_1.png
  public/assets/images/game/bg_2.png
  public/assets/images/game/bg_3.png
  public/assets/images/game/bg_4.png
  public/assets/images/game/cake.png
  public/assets/images/game/destna.png
  public/assets/images/game/donut.png
  public/assets/images/game/duch.png
  public/assets/images/game/ground.png
  public/assets/images/game/kralovstvi.png
  public/assets/images/game/krematorium.png
  public/assets/images/game/kunka.png
  public/assets/images/game/litomysl.png
  public/assets/images/game/matous.png
  public/assets/images/game/meat.png
  public/assets/images/game/opocno.png
  public/assets/images/game/pigeon_eat-Sheet.png
  public/assets/images/game/pigeon_eat_01.png
  public/assets/images/game/pigeon_eat_02.png
  public/assets/images/game/pigeon_eat_03.png
  public/assets/images/game/pigeon_eat_04.png
  public/assets/images/game/pigeon_fiy-Sheet.png
  public/assets/images/game/pigeon_fly_01.png
  public/assets/images/game/pigeon_fly_02.png
  public/assets/images/game/pigeon_fly_03.png
  public/assets/images/game/pigeon_fly_04.png
  public/assets/images/game/pigeon_fly_05.png
  public/assets/images/game/pigeon_fly_06.png
  public/assets/images/game/pigeon_fly_07.png
  public/assets/images/game/pigeon_walking-Sheet.png
  public/assets/images/game/pigeon_walking_01.png
  public/assets/images/game/pigeon_walking_02.png
  public/assets/images/game/pigeon_walking_03.png
  public/assets/images/game/pigeon_walking_04.png
  public/assets/images/game/rocket.png
  public/assets/images/game/space.png
  public/assets/images/game/tofu.png
  public/assets/images/game/vesmir.png
  yarn.lock
Labels: enhancement, PRIORITY

#19 Update holub-evzen.yml
  .github/workflows/holub-evzen.yml
Labels: enhancement

#20 Fix typo `evzen-holub.yml`
  .github/workflows/holub-evzen.yml
Labels: enhancement

#21 Update holub-evzen.yml
  .github/workflows/holub-evzen.yml
Labels: enhancement

#23 Update holub-evzen.yml
  .github/workflows/holub-evzen.yml
Labels: enhancement

#28 Improve automation
  .github/workflows/holub-evzen.yml
  lib/request.js
Labels: enhancement

#36 Improve pull request
  .github/workflows/holub-evzen.yml
Labels: enhancement

#38 New evzen score by `Pedro`
  _hall/1695211768985.json
Labels: evzen

#40 New evzen score by `BytovýTester`
  _hall/1695217225205.json
Labels: evzen

#41 New evzen score by `Pedro`
  _hall/1695219161288.json
Labels: evzen

#43 New evzen score by `Pedro`
  _hall/1695221885709.json
Labels: evzen

#42 Create hall of glory
  app/evzenova-cesta/page.js
  components/game.js
  components/layouts/container-description.js
  components/layouts/container-title.js
  lib/score.js
Labels: enhancement

#44 New evzen score by `Kajka`
  _hall/1695223032577.json
Labels: evzen

#47 New evzen score by `Kajka`
  _hall/1695223344157.json
Labels: evzen

#48 New evzen score by `Pedro`
  _hall/1695239167132.json
Labels: evzen

#50 New evzen score by `Bytový tester nejlepší hry z celého Vesmíru `
  _hall/1695243320877.json
Labels: evzen

#45 New evzen score by `Kajka`
  _hall/1695223042748.json
Labels: evzen

#51 New evzen score by `Davee`
  _hall/1695244963253.json
Labels: evzen

#49 New evzen score by `Bytový tester nejlepší hry z celého Vesmíru `
  _hall/1695243311422.json
Labels: evzen

#60 New evzen score by `Davee`
  _hall/1695281300783.json
Labels: evzen

#61 New evzen score by `Pedro`
  _hall/1695281693215.json
Labels: evzen

#64 New evzen score by `Pedro`
  _hall/1695289981233.json
Labels: evzen

#69 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: enhancement

#63 Create front page
  app/page.js
  components/layouts/container-description.js
  components/layouts/container-paragraph.js
  components/layouts/container-title.js
  components/layouts/container.js
  components/switcher.js
  components/switcher/diecezko-info.js
  components/switcher/program.js
  components/switcher/spolecenstvi-info.js
Labels: enhancement, content

#71 New evzen score by `Kajka`
  _hall/1695313577329.json
Labels: evzen

#72 Close Evzen adventure form box
  components/game.js
Labels: enhancement

#74 New evzen score by `Kajka`
  _hall/1695368323292.json
Labels: evzen

#75 New evzen score by `Pedro`
  _hall/1695379156230.json
Labels: evzen

#77 New evzen score by `Maky`
  _hall/1695393455858.json
Labels: evzen

#78 New evzen score by `Maky`
  _hall/1695393456492.json
Labels: evzen

#80 New evzen score by `Maky`
  _hall/1695393472774.json
Labels: evzen

#81 New evzen score by `Maky`
  _hall/1695393822983.json
Labels: evzen

#79 New evzen score by `Maky`
  _hall/1695393462533.json
Labels: evzen

#82 New evzen score by `Pedro`
  _hall/1695449250934.json
Labels: evzen

#83 New evzen score by `Domácí Petráskovic tester`
  _hall/1695491554883.json
Labels: evzen

#84 New evzen score by `Vojta V.`
  _hall/1695577927419.json
Labels: evzen

#88 New evzen score by `PePro`
  _hall/1695626490102.json
Labels: evzen

#89 New evzen score by `Maky`
  _hall/1695719992296.json
Labels: evzen

#91 New evzen score by `Daaveee_s_Praaheee`
  _hall/1695729617981.json
Labels: evzen

#92 New evzen score by `Jen`
  _hall/1695743786349.json
Labels: evzen

#93 Create section informace
  app/layout.js
  components/header.js
  components/images/adventni-cesta.js
  components/layouts/button.js
  components/layouts/card-feed.js
  components/layouts/card.js
  components/layouts/container-h3.js
  components/switcher.js
  components/switcher/spolecenstvi-info.js
  lib/switcher-context.js
  public/assets/images/adventni-cesta-white.svg
Labels: enhancement

#96 Update typo
  app/dczm-vesmir/page.js
Labels: bug

#97 New evzen score by `Kajka`
  _hall/1695814171625.json
Labels: evzen

#100 New evzen score by `Pedro`
  _hall/1695842710138.json
Labels: evzen

#101 Create stars
  lib/game.js
  public/assets/images/game/star.png
  public/assets/images/game/stars.png
Labels: enhancement

#102 Speed up game and add sound effects
  app/globals.css
  components/game.js
  lib/game.js
  public/assets/audio/background.mp3
  public/assets/audio/eating.mp3
  public/assets/audio/fail-effect.mp3
  public/assets/audio/star.mp3
  public/assets/audio/wingflap.mp3
Labels: enhancement

#104 New evzen score by `Pedro`
  _hall/1695882950864.json
Labels: evzen

#103 New evzen score by `Pedro`
  _hall/1695882950958.json
Labels: evzen

#106 Optimalize evzen adventures
  lib/game.js
Labels: bug, PRIORITY

#105 New evzen score by `PePro`
  _hall/1695887237404.json
Labels: evzen

#114 Limit nickname length
  _hall/1695217225205.json
  _hall/1695243311422.json
  _hall/1695243320877.json
  _hall/1695491554883.json
  components/game.js
  lib/game.js
  lib/request.js
Labels: bug, evzen

#115 Disable sound effects
  lib/game.js
Labels: bug
