Repository petrkucerak/diecezko.cz, pull requests merged in 2023-11, with the labels that each got.

#224 New evzen score by `KK`
  _hall/1698852781150.json
Labels: evzen

#223 New evzen score by `KK`
  _hall/1698852662296.json
Labels: evzen

#232 Add subtitle for targeting the kralovehradecka diocese
  components/countdown.js
  components/switcher/diecezko-info.js
Labels: enhancement

#234 New evzen score by `Yoro`
  _hall/1699194243521.json
Labels: evzen

#233 New evzen score by `Yoro`
  _hall/1699193527361.json
Labels: evzen

#235 New evzen score by `Pepek námořník `
  _hall/1699265837455.json
Labels: evzen

#236 New evzen score by `Pepek námořník `
  _hall/1699265849888.json
Labels: evzen

#237 New evzen score by `Ančí Máří`
  _hall/1699270306282.json
Labels: evzen

#238 New evzen score by `Animátoři`
  _hall/1699270497458.json
Labels: evzen

#242 New evzen score by `Slečna vedoucí`
  _hall/1699295513208.json
Labels: evzen

#243 New evzen score by `Yoro`
  _hall/1699305096770.json
Labels: evzen

#245 Update burger menu
  app/partneri/page.js
  components/header.js
Labels: enhancement, PRIORITY

#250 New evzen score by `Yoro`
  _hall/1699383828311.json
Labels: evzen

#251 New evzen score by `Yoro`
  _hall/1699384110960.json
Labels: evzen

#247 New evzen score by `kyyxxik`
  _hall/1699368924123.json
Labels: evzen

#249 Add partners
  app/partneri/page.js
  public/assets/images/sponsors/adalbertinum.svg
  public/assets/images/sponsors/bigy.png
  public/assets/images/sponsors/bigy.webp
  public/assets/images/sponsors/bihk.svg
  public/assets/images/sponsors/bistro.png
  public/assets/images/sponsors/bistro.webp
  public/assets/images/sponsors/fhk.svg
Labels: enhancement

#255 Fix locking scrolling bug
  components/header.js
Labels: bug, PRIORITY

#256 Update header.js
  components/header.js
Labels: bug, PRIORITY

#259 Remove intern nav links
  components/switcher/spolecenstvi-info.js
Labels: enhancement

#260 Base SEO
  app/opengraph-image.alt.txt
  app/opengraph-image.jpg
  app/sitemap.js
  app/twitter-image.alt.txt
  app/twitter-image.jpg
  components/footer.js
  public/assets/images/speakers/horak.webp
  public/assets/images/speakers/palusak.webp
  public/assets/images/speakers/vyborny.webp
  public/assets/images/sponsors/bigy.webp
  public/assets/images/sponsors/bistro.webp
Labels: enhancement

#262 Base SEO
  components/meta.js
Labels: enhancement

#265 Improve Iphone app experience
  app/partneri/page.js
  app/vikariaty/page.js
  components/meta.js
  components/switcher/diecezko-info.js
Labels: bug, enhancement, PRIORITY

#266 New evzen score by `Maky`
  _hall/1699536470362.json
Labels: evzen

#268 Create swaping gallery
  app/bistro-u-dvou-pratel/page.js
  app/globals.css
  components/swapping-gallery.js
  package.json
  public/assets/images/bistro/bistro_01.jpg
  public/assets/images/bistro/bistro_01.webp
  public/assets/images/bistro/bistro_02.jpg
  public/assets/images/bistro/bistro_02.webp
  public/assets/images/bistro/bistro_03.jpg
  public/assets/images/bistro/bistro_03.webp
  public/assets/images/bistro/bistro_04.jpg
  public/assets/images/bistro/bistro_04.webp
  public/assets/images/bistro/bistro_07.jpg
  public/assets/images/bistro/bistro_07.webp
  public/assets/images/bistro/bistro_08.jpg
  public/assets/images/bistro/bistro_08.webp
  public/assets/images/bistro/bistro_10.jpg
  public/assets/images/bistro/bistro_10.webp
  public/assets/images/bistro/bistro_11.jpg
  public/assets/images/bistro/bistro_11.webp
  public/assets/images/bistro/bistro_12.jpg
  public/assets/images/bistro/bistro_12.webp
  yarn.lock
Labels: enhancement

#270 Update content
  app/bistro-u-dvou-pratel/page.js
  app/dcm-hradec-kralove/page.js
  app/dczm-vesmir/page.js
  app/tyden-modliteb-za-mladez/page.js
  app/vikariaty/page.js
  components/swapping-gallery.js
  public/assets/images/spolecenstvi/dczm-vesmir-matous.jpg
  public/assets/images/spolecenstvi/dczm-vesmir-matous.webp
  public/assets/images/spolecenstvi/dczm-vesmir.jpg
  public/assets/images/spolecenstvi/dczm-vesmir.webp
  public/assets/images/spolecenstvi/diecezni-centrum-pro-mladez.jpg
  public/assets/images/spolecenstvi/diecezni-centrum-pro-mladez.png
  public/assets/images/spolecenstvi/diecezni-centrum-pro-mladez.webp
  public/assets/images/tmm.jpg
  public/assets/images/tmm.webp
  public/assets/images/vesmir/vesmir_00.jpg
  public/assets/images/vesmir/vesmir_00.webp
  public/assets/images/vesmir/vesmir_01.jpg
  public/assets/images/vesmir/vesmir_01.webp
  public/assets/images/vesmir/vesmir_02.jpg
  public/assets/images/vesmir/vesmir_02.webp
  public/assets/images/vesmir/vesmir_03.jpg
  public/assets/images/vesmir/vesmir_03.webp
  public/assets/images/vesmir/vesmir_04.jpg
  public/assets/images/vesmir/vesmir_04.webp
  public/assets/images/vesmir/vesmir_05.jpg
  public/assets/images/vesmir/vesmir_05.webp
  public/assets/images/vesmir/vesmir_06.jpg
  public/assets/images/vesmir/vesmir_06.webp
  public/assets/images/vesmir/vesmir_07.jpg
  public/assets/images/vesmir/vesmir_07.webp
  public/assets/images/vesmir/vesmir_08.jpg
  public/assets/images/vesmir/vesmir_08.webp
  public/assets/images/vesmir/vesmir_09.jpg
  public/assets/images/vesmir/vesmir_09.webp
  public/assets/images/vesmir/vesmir_10.jpg
  public/assets/images/vesmir/vesmir_10.webp
  public/assets/images/vesmir/vesmir_11.jpg
  public/assets/images/vesmir/vesmir_11.webp
  public/assets/images/vesmir/vesmir_12.jpg
  public/assets/images/vesmir/vesmir_12.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_01.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_01.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_02.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_02.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_03.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_03.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_04.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_04.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_05.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_05.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_06.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_06.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_07.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_07.webp
Labels: content

#271 New evzen score by `KAKABUS`
  _hall/1699612599063.json
Labels: evzen

#273 Update speaker details
  app/prednasky-workshopy/page.js
Labels: content

#272 New evzen score by `KAKABUS`
  _hall/1699613053586.json
Labels: evzen

#274 New evzen score by `Péťa`
  _hall/1699634803469.json
Labels: evzen

#275 New evzen score by `Péťa`
  _hall/1699640027705.json
Labels: evzen

#277 New evzen score by `Animátoři`
  _hall/1699692456873.json
Labels: evzen

#276 New evzen score by `Animátoři`
  _hall/1699651976078.json
Labels: evzen

#280 New evzen score by `Bety `
  _hall/1699790325832.json
Labels: evzen

#279 New evzen score by `Bety `
  _hall/1699790049203.json
Labels: evzen

#278 New evzen score by `Bety `
  _hall/1699787518961.json
Labels: evzen

#281 New evzen score by `Bety `
  _hall/1699790767110.json
Labels: evzen

#283 New evzen score by `Bety `
  _hall/1699794374486.json
Labels: evzen

#282 New evzen score by `Bety `
  _hall/1699794358227.json
Labels: evzen

#284 New evzen score by `Benda`
  _hall/1699816462462.json
Labels: evzen

#285 New evzen score by `Benda`
  _hall/1699816473180.json
Labels: evzen

#289 New evzen score by `Píďa`
  _hall/1699959815842.json
Labels: evzen

#290 New evzen score by `Píďa`
  _hall/1699959922909.json
Labels: evzen

#291 New evzen score by `Píďa`
  _hall/1699960313831.json
Labels: evzen

#293 New evzen score by `Gargamel`
  _hall/1699970603766.json
Labels: evzen

#294 New evzen score by `Gargamel`
  _hall/1699970612425.json
Labels: evzen

#295 New evzen score by `Nikolka`
  _hall/1699970887716.json
Labels: evzen

#296 New evzen score by `zdenucha`
  _hall/1699972977620.json
Labels: evzen

#297 New evzen score by `Šmudla`
  _hall/1699975018614.json
Labels: evzen

#298 New evzen score by `Ignac`
  _hall/1699978946723.json
Labels: evzen

#299 New evzen score by `Džitka`
  _hall/1700039541773.json
Labels: evzen

#300 New evzen score by `Vojta`
  _hall/1700057279392.json
Labels: evzen

#301 New evzen score by `Vojta`
  _hall/1700057280783.json
Labels: evzen

#302 New evzen score by `Vojta`
  _hall/1700057453497.json
Labels: evzen

#304 New evzen score by `Sojta`
  _hall/1700058556176.json
Labels: evzen

#306 New evzen score by `Ignac`
  _hall/1700077436831.json
Labels: evzen

#307 New evzen score by `KikiTýnaJu`
  _hall/1700089017703.json
Labels: evzen

#309 New evzen score by `Džusika`
  _hall/1700127084168.json
Labels: evzen

#308 New evzen score by `Džusika`
  _hall/1700127076401.json
Labels: evzen

#310 New evzen score by `Džusika`
  _hall/1700127290180.json
Labels: evzen

#311 New evzen score by `Džusika`
  _hall/1700127426089.json
Labels: evzen

#312 New evzen score by `Džusika`
  _hall/1700127591229.json
Labels: evzen

#313 New evzen score by `tvoje máma `
  _hall/1700133401202.json
Labels: evzen

#316 New evzen score by `Lipen`
  _hall/1700150519633.json
Labels: evzen

#315 New evzen score by `Lipen`
  _hall/1700150201729.json
Labels: evzen

#317 New evzen score by `Tery z Plzně`
  _hall/1700155783196.json
Labels: evzen

#318 New evzen score by `Markyyyy`
  _hall/1700157915371.json
Labels: evzen

#319 New evzen score by `Markyyyy`
  _hall/1700158106883.json
Labels: evzen

#320 New evzen score by `Markyyyy`
  _hall/1700158109178.json
Labels: evzen

#321 New evzen score by `Ignac`
  _hall/1700163072135.json
Labels: evzen

#324 New evzen score by `spolčo nováč`
  _hall/1700223650988.json
Labels: evzen

#326 Create the 404 page
  app/not-found.js
  public/assets/images/404.png
  public/assets/images/404.webp
Labels: enhancement

#327 New evzen score by `Džitka`
  _hall/1700235204858.json
Labels: evzen

#329 Improve copy
  app/dczm-vesmir/page.js
  app/jadro-diecezka/page.js
  app/kak-salas/page.js
  app/veka/page.js
  components/faq.js
  components/switcher/diecezko-info.js
Labels: content

#334 New evzen score by `Džitka`
  _hall/1700296237700.json
Labels: evzen

#333 New evzen score by `Džitka`
  _hall/1700296229701.json
Labels: evzen

#332 New evzen score by `Džitka`
  _hall/1700296243452.json
Labels: evzen

#331 New evzen score by `Džitka`
  _hall/1700296256691.json
Labels: evzen

#330 New evzen score by `Džitka`
  _hall/1700296265156.json
Labels: evzen

#335 New evzen score by `Džitka`
  _hall/1700297831470.json
Labels: evzen

#336 New evzen score by `Džitka`
  _hall/1700299958333.json
Labels: evzen

#337 New evzen score by `BB`
  _hall/1700327797194.json
Labels: evzen

#339 Add medical contact
  components/faq.js
  components/layouts/faq-box.js
Labels: content

#344 New evzen score by `Bruh`
  _hall/1700343984080.json
Labels: evzen

#345 New evzen score by `Bruh`
  _hall/1700344018753.json
Labels: evzen

#343 Update images to vikariat
  app/vikariaty/page.js
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_08.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_08.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_09.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_09.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_10.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_10.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_11.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_11.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_12.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_12.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_13.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_13.webp
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_14.jpg
  public/assets/images/vikariaty-skupinove/vikariaty_skupinove_14.webp
Labels: content

#346 New evzen score by `Java`
  _hall/1700344126791.json
Labels: evzen

#347 New evzen score by `Java`
  _hall/1700344132954.json
Labels: evzen

#349 Add denik sracu interaction
  app/mse-svata/page.js
  components/images/deniksracu.js
  components/switcher/spolecenstvi-info.js
  public/assets/images/deniksracu.svg
Labels: content

#350 New evzen score by `Justus`
  _hall/1700387471464.json
Labels: evzen

#351 New evzen score by `Vysoká Verčaa`
  _hall/1700388557272.json
Labels: evzen

#352 New evzen score by `Vysoká Verčaa`
  _hall/1700388585536.json
Labels: evzen

#353 New evzen score by `Vysoká Verčaa`
  _hall/1700388606804.json
Labels: evzen

#354 New evzen score by `Vysoká Verčaa`
  _hall/1700389527629.json
Labels: evzen

#356 New evzen score by `Vojťák z Dohalic`
  _hall/1700390138863.json
Labels: evzen

#357 New evzen score by `Vojťák z Dohalic`
  _hall/1700390154424.json
Labels: evzen

#355 Add link to playlist
  app/mse-svata/page.js
Labels: enhancement

#363 New evzen score by `Vojťák z Dohalic`
  _hall/1700390869902.json
Labels: evzen

#362 New evzen score by `Vojťák z Dohalic`
  _hall/1700390867552.json
Labels: evzen

#364 New evzen score by `Vojťák z Dohalic`
  _hall/1700390872014.json
Labels: evzen

#365 New evzen score by `Vojťák z Dohalic`
  _hall/1700390874528.json
Labels: evzen

#361 New evzen score by `Vojťák z Dohalic`
  _hall/1700390862172.json
Labels: evzen

#366 New evzen score by `Vojťák z Dohalic`
  _hall/1700390931234.json
Labels: evzen

#367 New evzen score by `Vojťák z Dohalic`
  _hall/1700390948723.json
Labels: evzen

#368 New evzen score by `Janurb`
  _hall/1700390667328.json
Labels: evzen

#369 New evzen score by `Vysoká Verčaa`
  _hall/1700391151205.json
Labels: evzen

#373 New evzen score by `Vojťák z Dohalic`
  _hall/1700393231051.json
Labels: evzen

#374 New evzen score by `Vojťák z Dohalic`
  _hall/1700393236166.json
Labels: evzen

#375 New evzen score by `Vojťák z Dohalic`
  _hall/1700393240359.json
Labels: evzen

#376 New evzen score by `ezz`
  _hall/1700402304501.json
Labels: evzen

#377 New evzen score by `haha`
  _hall/1700403176659.json
Labels: evzen

#378 New evzen score by `Péťa`
  _hall/1700407789922.json
Labels: evzen

#379 New evzen score by `ezz`
  _hall/1700407801190.json
Labels: evzen

#380 New evzen score by `Péťa`
  _hall/1700408295614.json
Labels: evzen

#381 New evzen score by `Ignac`
  _hall/1700408562304.json
Labels: evzen

#388 New evzen score by `Pavel_vac`
  _hall/1700413518628.json
Labels: evzen

#389 New evzen score by `Pavel_vac`
  _hall/1700413529396.json
Labels: evzen

#384 New evzen score by `poslední`
  _hall/1700412591695.json
Labels: evzen

#383 New evzen score by `poslední`
  _hall/1700412321009.json
Labels: evzen

#387 New evzen score by `Máří z Dohalic`
  _hall/1700413100459.json
Labels: evzen

#392 New evzen score by `Žena Posledního `
  _hall/1700417893815.json
Labels: evzen

#390 New evzen score by `Vojťák z Dohalic`
  _hall/1700416442963.json
Labels: evzen

#391 New evzen score by `Vojťák z Dohalic`
  _hall/1700417030630.json
Labels: evzen

#393 New evzen score by `Kryštofus`
  _hall/1700461166088.json
Labels: evzen

#394 New evzen score by `Kryštofus`
  _hall/1700461171295.json
Labels: evzen

#395 New evzen score by `JB`
  _hall/1700467034695.json
Labels: evzen

#396 New evzen score by `JB`
  _hall/1700467046213.json
Labels: evzen

#397 New evzen score by `BeeXík`
  _hall/1700476654422.json
Labels: evzen

#398 New evzen score by `BeeXík`
  _hall/1700477079579.json
Labels: evzen

#399 New evzen score by `Jan`
  _hall/1700477229226.json
Labels: evzen

#403 Hide deniksracu
  components/faq.js
  components/layouts/faq-box.js
  components/switcher/spolecenstvi-info.js
Labels: enhancement

#405 New evzen score by `Anež`
  _hall/1700584446550.json
Labels: evzen

#406 New evzen score by `Ančí z Dohalic`
  _hall/1700591217752.json
Labels: evzen

#407 New evzen score by `Péťa`
  _hall/1700592557614.json
Labels: evzen

#408 New evzen score by `Péťa`
  _hall/1700593330519.json
Labels: evzen

#410 New evzen score by `Dl`
  _hall/1700634602404.json
Labels: evzen

#411 New evzen score by `Jirka`
  _hall/1700635178267.json
Labels: evzen

#412 New evzen score by `Slečna vedoucí`
  _hall/1700662962109.json
Labels: evzen

#414 New evzen score by `Yoro`
  _hall/1700676673191.json
Labels: evzen

#415 New evzen score by `Píďa`
  _hall/1700676934756.json
Labels: evzen

#418 Update page.js
  app/evzenova-lovestory/page.js
Labels: content

#419 Evzen LOVESTORY
  app/evzenova-lovestory/evzen-rust-je-dobry/page.js
  app/evzenova-lovestory/evzen-vzdech-je-slyset-do-daly/page.js
  app/evzenova-lovestory/evzenka-z-bona-na-jedno/page.js
Labels: content, evzen

#420 New evzen score by `whasssup`
  _hall/1700728991282.json
Labels: evzen

#422 New evzen score by `Pinky Pie`
  _hall/1700758881631.json
Labels: evzen

#424 New evzen score by `Pinky Pie`
  _hall/1700759009845.json
Labels: evzen

#426 New evzen score by `cdwifi.cz`
  _hall/1700772579534.json
Labels: evzen

#428 Add link to florball match
  components/switcher/spolecenstvi-info.js
Labels: enhancement

#430 Try new precache strategy
  custom-cache.js
Labels: enhancement, PRIORITY

#433 Create feedback button
  components/switcher/diecezko-info.js
  custom-cache.js
Labels: enhancement

#435 Fix evzen bug
  app/evzenova-lovestory/page.js
Labels: enhancement

#437 New evzen score by `TeryC`
  _hall/1700849043382.json
Labels: evzen
